name:                megarecord
version:             0.1.0.0
synopsis:            Extensible records and Rows
homepage:            https://github.com/jvanbruegge/megarecord#readme
license:             Apache-2.0
author:              Jan van Brügge
maintainer:          supermanitu@gmail.com
copyright:           2018 Jan van Brügge
category:            Web
extra-source-files:
- README.md

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints

dependencies:
  - base >= 4.7 && < 5
  - first-class-families

executable:
    source-dirs:      src
    main:             Main.hs
    dependencies:
      - megarecord

library:
  source-dirs: src
  exposed-modules:
    - Megarecord

default-extensions:
    - BangPatterns
    - DataKinds
    - EmptyDataDecls
    - FlexibleInstances
    - FunctionalDependencies
    - KindSignatures
    - MultiParamTypeClasses
    - PolyKinds
    - ScopedTypeVariables
    - TypeApplications
    - TypeFamilies
    - TypeOperators
    - TypeInType
    - UndecidableInstances
